[project]
name = "Thoth-dhwtj"
version = "1.0.0"
description = "Maintain the Ma'at of Secure Software Development"
license="Apache-2.0"
authors = [
    {name = "Eric Nieuwland", email = "eric.nieuwland@ictu.nl"},
]
readme = "README.md"
requires-python = ">= 3.13"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Pydantic",
    "Framework :: Typer",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Topic :: Documentation",
]
dependencies = [
    "pydantic==2.11.3",
    "python-docx==1.1.2",
    "pyyaml==6.0.2",
    "typer==0.15.2",
]

[tool.setuptools.packages.find]
include = ["thoth", "docs"]

[project.optional-dependencies]
test = [
    "mypy==1.15.0",
    "pytest==8.3.5",
    "pytest-cov==6.1.1",
    "ruff==0.11.4",
]

[tool.ruff]
target-version = "py313"
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle
    "I",   # isort
    "ANN", # flake8 type annotations
    "RUF", # ruff-specific rules
]
fixable = ["ALL"]

[tool.mypy]
python_version = "3.13"
